class KinectConfigs :
    DEPTH_MODE_OFF = 0
    DEPTH_MODE_NFOV_2X2BINNED = 1
    DEPTH_MODE_NFOV_UNBINNED = 2
    DEPTH_MODE_WFOV_2X2BINNED = 3
    DEPTH_MODE_WFOV_UNBINNED = 4
    DEPTH_MODE_PASSIVE_IR = 5
    
    COLOR_RESOLUTION_OFF = 0
    COLOR_RESOLUTION_720P = 1
    COLOR_RESOLUTION_1080P = 2
    COLOR_RESOLUTION_1440P = 3
    COLOR_RESOLUTION_1536P = 4
    COLOR_RESOLUTION_2160P = 5
    COLOR_RESOLUTION_3072P = 6